{
  "hash": "71cdf5ca60d26b7b2c2d1b3baa112cf4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Assignment 05\"\nformat: \n        html: default\n        pdf: default\nauthor: \"Christina Dai\"\ndate: \"2026-02-25\"\n---\n\n::: {#37d44627 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\ndf = pd.read_csv(\"wdi.csv\")\n```\n:::\n\n\n## Conducting Exploratory Data Analysis\n\nIn this report we will be focusing on the following 3 variables in order to better understand the global landscape in 2022:\n\n1.  **primary_school_enrolment_rate:** measures the percentage of children of official primary school age who are enrolled in primary education.\n\n2.  **life_expectancy:** is the average number of years someone is expected to live\n\n3.  **unemployment_rate:** measures the percentage of the total labor force that is without work but are able to work/ looking for work.\n\n### Primary School Enrollment EDA\n\n::: {#primary_school_enrolment_rate_eda .cell execution_count=2}\n``` {.python .cell-code}\nprim_enrol = df['primary_school_enrolment_rate']\n\nprim_enrol_clean = prim_enrol.dropna()\n\nprint(\"Mean:\", prim_enrol_clean.mean())\nprint(\"Median:\", prim_enrol_clean.median())\nprint(\"Standard Deviation:\", prim_enrol_clean.std())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean: 100.87404840034348\nMedian: 100.0222473144529\nStandard Deviation: 12.037531967222588\n```\n:::\n:::\n\n\nThe mean for primary school enrollment for 2022 was approximately 100.87% enrollment rate with a standard deviation of about 11.98%. The median is around 100% enrollment rate.\n\n### Life Expectancy EDA\n\n::: {#life_expectancy_eda .cell execution_count=3}\n``` {.python .cell-code}\nlife_exp = df['life_expectancy']\n\nlife_exp_clean = life_exp.dropna()\n\nprint(\"Mean:\", life_exp_clean.mean())\nprint(\"Median:\", life_exp_clean.median())\nprint(\"Standard Deviation:\", life_exp_clean.std())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean: 72.4165186136072\nMedian: 73.5146341463415\nStandard Deviation: 7.713322276991691\n```\n:::\n:::\n\n\nThe mean for life expectancy for 2022 was approximately 72.42 years old with a standard deviation of about 7.71 years. The median is around 73.51 years old.\n\n### Unemployment Rate EDA\n\n::: {#unemployment_rate_eda .cell execution_count=4}\n``` {.python .cell-code}\nunempl_rate = df['unemployment_rate']\n\nunempl_rate_clean = unempl_rate.dropna()\n\nprint(\"Mean:\", unempl_rate_clean.mean())\nprint(\"Median:\", unempl_rate_clean.median())\nprint(\"Standard Deviation:\", unempl_rate_clean.std())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean: 7.268661290322581\nMedian: 5.5375\nStandard Deviation: 5.827726289581319\n```\n:::\n:::\n\n\nThe mean for unemployment rate for 2022 was approximately 7.27% with a standard deviation of about 5.83%. The median is around 5.54% unemployment rate.\n\n## Scatterplot (life expectancy vs unemployment rate)\n\n::: {#cell-fig-life-unemployment .cell execution_count=5}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nd = df[['life_expectancy', 'unemployment_rate']].dropna()\n\nplt.figure()\nplt.scatter(d['unemployment_rate'], d['life_expectancy'])\nplt.title(\"Life Expectancy vs Unemployment Rate (2022)\")\nplt.xlabel(\"Unemployment rate (%)\")\nplt.ylabel(\"Life expectancy (years)\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Life expectancy vs. unemployment rate in 2022. Source: @worldbank_wdi_2022.](Assignment 05_files/figure-html/fig-life-unemployment-output-1.png){#fig-life-unemployment width=585 height=449}\n:::\n:::\n\n\n## Histogram (primary school enrollment rate)\n\n::: {#cell-fig-enrolment-hist .cell execution_count=6}\n``` {.python .cell-code}\nd = df['primary_school_enrolment_rate'].dropna()\n\nplt.figure()\nplt.hist(d, bins=30)\nplt.title(\"Primary School Enrollment Rate (2022)\")\nplt.xlabel(\"Primary school enrolment rate (%)\")\nplt.ylabel(\"Number of Countries per Rate\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Primary school enrolment rate distribution (WDI 2022). Source: @worldbank_wdi_2022.](Assignment 05_files/figure-html/fig-enrolment-hist-output-1.png){#fig-enrolment-hist width=598 height=449}\n:::\n:::\n\n\n## Key Statistics\n\n::: {#tbl-key-stats .cell tbl-cap='Key summary statistics for selected indicators (WDI 2022). Source: @worldbank_wdi_2022.' execution_count=7}\n``` {.python .cell-code}\n# Select variables and remove missing values\nd = df[['primary_school_enrolment_rate',\n        'life_expectancy',\n        'unemployment_rate']]\n\nsummary = pd.DataFrame({\n    \"Mean\": d.mean(),\n    \"Median\": d.median(),\n    \"Standard Deviation\": d.std(),\n    \"Minimum\": d.min(),\n    \"Maximum\": d.max()\n})\n\nsummary\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Mean</th>\n      <th>Median</th>\n      <th>Standard Deviation</th>\n      <th>Minimum</th>\n      <th>Maximum</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>primary_school_enrolment_rate</th>\n      <td>100.874048</td>\n      <td>100.022247</td>\n      <td>12.037532</td>\n      <td>64.395401</td>\n      <td>138.192001</td>\n    </tr>\n    <tr>\n      <th>life_expectancy</th>\n      <td>72.416519</td>\n      <td>73.514634</td>\n      <td>7.713322</td>\n      <td>52.997000</td>\n      <td>85.377000</td>\n    </tr>\n    <tr>\n      <th>unemployment_rate</th>\n      <td>7.268661</td>\n      <td>5.537500</td>\n      <td>5.827726</td>\n      <td>0.130000</td>\n      <td>37.852000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Conclusion\nAs shown in @fig-life-unemployment, there appears to be a negative association between unemployment rates and life expectancy in 2022. Countries with lower unemployment rates generally tend to exhibit higher life expectancy, suggesting that stronger labor markets may be associated with better overall life quality and life expectancy.\n\nStudies have shown that unemployment rates and other related socioeconomic factors are associated with mortality and life expectancy. For example, research shows that long-term unemployment correlates with reduced life expectancy and greater disability over time [@laditka_unemployment_disability_life_expectancy_2016], and the protective effect of employment on longevity varies by race, gender, and education [@assari_employment_life_expectancy_2017].\n\n@fig-enrolment-hist illustrates that the primary school enrollment rate distribution is approximately unimodal and centered around 100%. The distribution appears relatively concentrated near full enrollment, though several countries exhibit enrollment rates exceeding 100%. This is consistent with the use of a gross enrollment rate measure, which can exceed 100% due to the inclusion of over-aged or under-aged students enrolled in primary education.\n\nThe key summary statistics are reported in @tbl-key-stats, which highlights variation across indicators. \n\n",
    "supporting": [
      "Assignment 05_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}